# This is the default config. It is not ideal to make changes to this.
# Make a user.yml in the same directory to add or modify categories.
#
# Example user.yml:
# categories:
#   - name: 3d
#     dir: 3d # (optional, default: name)
#     override: true # (optional, default: false. When true, it overrides an existing category, extends otherwise)
#     extensions:
#       - blender
#       - fbx
#       - obj

categories:
  - name: audio
    dir: audio
    extensions:
      - mp3
      - wav
      - flac
      - aac
      - ogg
      - m4a
      - wma
      - alac
      - aiff
      - opus

  - name: archive
    dir: archive 
    extensions:
      - zip
      - rar
      - 7z
      - tar
      - iso
      - cab
      - arj

  - name: compressed
    dir: compressed 
    extensions:
      - gz
      - bz2
      - xz
      - lz
      - lzma
      - zst

  - name: document
    dir: document 
    extensions:
      - pdf
      - doc
      - docx
      - txt
      - odt
      - rtf
      - tex
      - md

  - name: photo
    dir: photo 
    extensions:
      - jpg
      - jpeg
      - png
      - gif
      - bmp
      - tiff
      - svg
      - webp
      - heic
      - raw

  - name: presentation
    dir: presentation 
    extensions:
      - ppt
      - pptx
      - odp
      - key

  - name: spreadsheet
    dir: spreadsheet 
    extensions:
      - xls
      - xlsx
      - xlsm
      - ods
      - csv
      - tsv
      - xlsb
      - xlt
      - xltx

  - name: video
    dir: video 
    extensions:
      - mp4
      - mkv
      - mov
      - avi
      - webm
      - flv
      - wmv
      - m4v
      - 3gp
